services:

  peer1:
    build: .
    container_name: peer1
    stdin_open: true
    tty: true
    environment:
      - INSTITUTION=peer1
    volumes:
      - ./data/peer1:/app/data # peer1 .parquet files
      - peer1_cache:/app/cache # isolated cache
    networks:
      - p2p-net

  peer2:
    build: .
    container_name: peer2
    stdin_open: true
    tty: true
    environment:
        INSTITUTION: peer2
        BOOTSTRAP_PEERS: "acf5d6d54a6a62970b04cc1ca51db5dc72797d686d0d7c3d30adf0f0ae39b8a1" # Enter the nodeID from peer1 here
    volumes:
      - ./data/peer2:/app/data # peer1 .parquet files
      - peer2_cache:/app/cache # isolated cache
    networks:
      - p2p-net

  peer3:
    build: .
    container_name: peer3
    stdin_open: true
    tty: true
    environment:
        INSTITUTION: peer3
        BOOTSTRAP_PEERS: "acf5d6d54a6a62970b04cc1ca51db5dc72797d686d0d7c3d30adf0f0ae39b8a1" # Enter the nodeID from peer1 here
    volumes:
      - ./data/peer3:/app/data # peer1 .parquet files
      - peer3_cache:/app/cache # isolated cache
    networks:
      - p2p-net

volumes:
  peer1_cache:
  peer2_cache:
  peer3_cache:

networks:
  p2p-net:
    driver: bridge