# References: https://docs.docker.com/compose/how-tos/networking/
services:

  peer1:
    build: .
    container_name: peer1
    stdin_open: true
    tty: true
    environment:
      - INSTITUTION=peer1
    volumes:
      - ./data/peer1:/app/data # peer1 .parquet files
      - peer1_cache:/app/cache # isolated cache
    networks:
      - p2p-net

  peer2:
    build: .
    container_name: peer2
    stdin_open: true
    tty: true
    environment:
        INSTITUTION: peer2
        BOOTSTRAP_PEERS: "f865b4d92bfb0005aa8486a1349b47f54e9201b29907d79c874831fa314a6374" # Enter the nodeID from peer1 here
    volumes:
      - ./data/peer2:/app/data # peer1 .parquet files
      - peer2_cache:/app/cache # isolated cache
    networks:
      - p2p-net

  peer3:
    build: .
    container_name: peer3
    stdin_open: true
    tty: true
    environment:
        INSTITUTION: peer3
        BOOTSTRAP_PEERS: "f865b4d92bfb0005aa8486a1349b47f54e9201b29907d79c874831fa314a6374" # Enter the nodeID from peer1 here
    volumes:
      - ./data/peer3:/app/data # peer1 .parquet files
      - peer3_cache:/app/cache # isolated cache
    networks:
      - p2p-net

volumes:
  peer1_cache:
  peer2_cache:
  peer3_cache:

networks:
  p2p-net:
    driver: bridge